apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels: 
    app: app-server
spec: 
  selector:
    matchLabels:
      app: app-server
  template: 
    metadata: 
      labels:
        app: app-server
    spec:
      containers:
      - image: nginx:1.21
        name: web-server
        ports:
        - containerPort: 80
